#!/usr/bin/env python


print("      ___________________________________")                           
print("     |          |               |        |")
print("     | USUARIOS |  PUNTUACIONES | TIEMPO |")
print("     |__________|_______________|________|")
                         

						 
