#!/usr/bin/env python


def print


print("      ___________________________________")                 
print("     |          |               |        |")
print("     | USUARIOS |  PUNTUACIONES | TIEMPO |")
print("     |__________|_______________|________|")



