#!/usr/bin/env python3
                                                              

print("                                                                                    _") 
print(" _______         ______         _______         ______         _______             |_|         ")
print("/___ ___\\       |  __  |       /__   __\       |  ____|       /__   __\                      ") 
print("   | |  ______  | |__| |  ______  | |  ______  | |____   ______  | |     _______   | |       ")
print("   | | |______| | |  | | |______| | | |______| | _____| |______| | |    |_______|  | |        ") 
print("   | |          | |  | |          | |          | |____           | |               | |       ")  
print("   |_|          |_|  |_|          |_|          |______|          |_|               |_|         ")



print("                                                  

print("*Para jugar ta-te-ti, debes elejir entre (X / O) , y lograr hacer 3 en raya , el primero jugador en hacerlo gana...")
print("tus opciones, estan definidas por numeros del 1 al 9...") 

print ("                       ")
                                                         														  
print("_______________") 
print("                ") 
print("> PLAY GAME < ")
print("> HIGH SCORES < ") 
print("> QUIT GAME < ")
print ("_______________")






                             
