#!/usr/bin/env python3
                                                               
print("                                                _____  ")
print(" _______         ______         _______        |   __| ")
print("/___ ___\\       |  __  |       /__   __\       |  |__   ") 
print("   | |  ______  | |__| |  ______  | |  ______  |   __|    ")
print("   | | |______| | |  | | |______| | | |______| |  |__  ")  
print("   |_|          |_|  |_|          |_|          |_____|      ")     
print("                                                        ")   

print("                                                                                          ")

print("*Para jugar ta-te-ti, debes elejir entre (X / O) , y lograr hacer 3 en raya , el primero jugador en hacerlo gana...")
print("tus opciones, estan definidas por numeros del 1 al 9...") 

print ("                       ")
                                                         														  
print("________________") 
print("                ") 
print(" > PLAY GAME < ")
print(" > HIGH SCORES < ") 
print(" > QUIT GAME < ")
print ("_______________")






                             
